#    Nhỏ   (nhanh)   : COLS=15,  ROWS=15,  CELL_SIZE=36
#    Vừa   (mặc định): COLS=25,  ROWS=25,  CELL_SIZE=28
#    Lớn             : COLS=41,  ROWS=41,  CELL_SIZE=17
#    Rất lớn         : COLS=61,  ROWS=61,  CELL_SIZE=11
#    Siêu lớn        : COLS=101, ROWS=101, CELL_SIZE=7

COLS = 41
ROWS = 41
CELL_SIZE = 17

COLS = COLS if COLS % 2 == 1 else COLS + 1
ROWS = ROWS if ROWS % 2 == 1 else ROWS + 1

MAZE_X_OFFSET = 20
MAZE_Y_OFFSET = 80
PANEL_WIDTH = 340
WINDOW_W = COLS * CELL_SIZE + MAZE_X_OFFSET * 2 + PANEL_WIDTH
WINDOW_H = max(ROWS * CELL_SIZE + MAZE_Y_OFFSET + 58, 780)

SHOW_PANEL_TITLE = False
SHOW_PANEL_EMPTY_HINT = False
SHOW_PANEL_COMPARISON = False
SHOW_PANEL_EXPLANATIONS = False
SHOW_STATUS_BAR = False
SHOW_LEGEND = True
SHOW_BOTTOM_HINT = False
SHOW_COMPARE_TABLE_HINT = False
SHOW_CONSOLE_STATS = False
SHOW_CONSOLE_EXPLANATIONS = False