COLS = 25
ROWS = 25
CELL_SIZE = 28

COLS = COLS if COLS % 2 == 1 else COLS + 1
ROWS = ROWS if ROWS % 2 == 1 else ROWS + 1

MAZE_X_OFFSET = 20
MAZE_Y_OFFSET = 80
PANEL_WIDTH = 340
WINDOW_W = COLS * CELL_SIZE + MAZE_X_OFFSET * 2 + PANEL_WIDTH
WINDOW_H = max(ROWS * CELL_SIZE + MAZE_Y_OFFSET + 58, 780)